(function(){
"use strict";
const LP="hyphsworld.coolPoints.total",RK="hyphsworld.casinoArcade.recent";
const CDN="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2",CFG="supabase-config.js";
const G={
crash:["Crash","RISK TIMING","Pick a target multiplier. If the rocket clears it before crashing, you collect bonus Cool Points.","01_crash_arcade"],
plinko:["Plinko","GRAVITY DROP","Drop the neon ball through the pegs. The bucket decides the bonus.","01_plinko_arcade"],
mines:["Mines","SAFE TILE CHASE","Reveal safe tiles and cash out the bonus before Duck Sauce steps on a mine.","01_mines_arcade"],
slots:["Neon Slots","3-REEL SPIN","Spin the HYPHSWORLD reels. Matching symbols add bonus Cool Points.","01_neon_slots"],
scratcher:["Scratcher","REVEAL CARD","Reveal six panels. Three matching icons hit the bonus.","01_scratcher"],
hilo:["High-Low","CARD STREAK","Guess higher or lower. Each correct call builds the bonus streak.","01_high_low"],
roulette:["Roulette","COLOR SPIN","Pick red, black, or green. The wheel spins for bonus Cool Points.","01_roulette"]
};
const SY=["💎","🧢","🦆","🔥","🎹","💵","🎲","🌉"],PM=[0,1,2,4,8,12,8,4,2,1,0],CV=[2,3,4,5,6,7,8,9,10,11,12,13,14];
let game="crash",user=null,sbp=null,mines=null,hilo=null,scratch=null,rot=0;
const $=id=>document.getElementById(id),q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const rnd=n=>Math.floor(Math.random()*n),cl=(n,a,b)=>Math.max(a,Math.min(b,n)),num=v=>{let p=parseInt(v,10);return Number.isFinite(p)&&p>0?p:0},fmt=v=>new Intl.NumberFormat("en-US").format(num(v));
const safe=v=>String(v||"").replace(/[<>]/g,"").trim();
function txt(id,v){let e=$(id);if(e)e.textContent=v}
function status(v){txt("casinoStatus",v)}
function power(){let i=$("casinoPowerInput"),v=cl(num(i&&i.value),1,1000);if(i)i.value=v;return v}
function lp(){try{return num(localStorage.getItem(LP))}catch{return 0}}
function slp(v){try{localStorage.setItem(LP,String(Math.max(0,num(v))))}catch{}}
function rec(){try{return JSON.parse(localStorage.getItem(RK)||"[]")}catch{return[]}}
function saveRec(x){let r=[x].concat(rec()).slice(0,5);try{localStorage.setItem(RK,JSON.stringify(r))}catch{};drawRec()}
function drawRec(){let l=$("casinoRecentList"),r=rec();if(!l)return;l.innerHTML=r.length?r.map(x=>`<span>${safe(x.g)} • +${fmt(x.p)} • ${safe(x.r)}</span>`).join(""):"<span>No hits yet.</span>"}
function load(src){return new Promise((res,rej)=>{let old=Array.from(document.scripts).find(s=>s.src&&s.src.includes(src));if(old){old.addEventListener("load",res,{once:true});setTimeout(res,200);return}let s=document.createElement("script");s.src=src;s.async=false;s.onload=res;s.onerror=()=>rej(new Error("Could not load "+src));document.head.appendChild(s)})}
async function sb(){if(sbp)return sbp;sbp=(async()=>{try{if(!window.HW_SUPABASE_CONFIG)await load(CFG);let c=window.HW_SUPABASE_CONFIG||{},u=String(c.url||""),k=String(c.anonKey||c.anon_key||"");if(!u||!k||/PASTE_|YOUR_|PROJECT_URL|ANON_PUBLIC_KEY/i.test(u+k))return null;if(!window.supabase||!window.supabase.createClient)await load(CDN);return window.supabase&&window.supabase.createClient?window.supabase.createClient(u,k,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null}catch{return null}})();return sbp}
async function refreshUser(){let a=$("casinoAuthLink");try{user=window.HWAuth&&await window.HWAuth.getCurrentUser()}catch{user=null}if(user&&user.email){txt("casinoPlayerName",user.displayName||user.username||user.email);txt("casinoPlayerMode","Logged in. Wins can save to Cool Points and the game board.");txt("casinoPoints",fmt(user.coolPoints||0));if(a){a.textContent="Manage ID";a.href="account.html"}}else{txt("casinoPlayerName","Guest Player");txt("casinoPlayerMode","Guest mode. Create ID to keep scores across devices.");txt("casinoPoints",fmt(lp()))}}
async function addPts(p,reason){p=Math.max(0,Math.round(p||0));if(!p)return;try{if(window.HWAuth&&window.HWAuth.addPoints){let n=await window.HWAuth.addPoints(p,reason);txt("casinoPoints",fmt(n));await refreshUser();return}}catch(e){console.warn("points",e&&e.message||e)}let n=lp()+p;slp(n);txt("casinoPoints",fmt(n))}
async function saveScore(g,score,p,meta){if(!user||!user.userId||user.provider==="mock")return;try{let c=await sb();if(!c)return;await c.from("game_scores").insert({user_id:user.userId,game_key:G[g][3],score:Math.max(1,Math.round(score||p||1)),points_delta:Math.max(0,Math.round(p||0)),metadata:Object.assign({source:"casino_arcade",no_real_money:true},meta||{})})}catch(e){console.warn("score",e&&e.message||e)}}
async function award(g,p,score,result,meta){p=Math.max(0,Math.round(p||0));if(p){await addPts(p,G[g][3]+"_win");await saveScore(g,score||p,p,Object.assign({result},meta||{}));saveRec({g:G[g][0],p:p,r:result||"win"});status(`${G[g][0]} hit +${fmt(p)} Cool Points. Your points were never reduced.`)}else{await saveScore(g,score||1,0,Object.assign({result:result||"no_bonus"},meta||{}));status("No bonus this round. Cool Points stayed untouched — this floor does not subtract points.")}}
const btn=(t,a,c="")=>`<button class="arcade-btn ${c}" type="button" data-action="${a}">${t}</button>`;
const field=(lab,id,html,note="")=>`<label class="casino-field" for="${id}"><span>${lab}</span>${html}${note?`<small>${note}</small>`:""}</label>`;
function setGame(g){game=g;mines=hilo=scratch=null;qa("[data-game]").forEach(b=>b.classList.toggle("is-active",b.dataset.game===g));txt("casinoGameTitle",G[g][0]);txt("casinoGameKicker",G[g][1]);txt("casinoGameDescription",G[g][2]);render()}
function bind(){qa("[data-action]").forEach(b=>b.onclick=()=>act(b.dataset.action))}
function render(){
let s=$("casinoStage"),c=$("casinoControls");if(!s||!c)return;
if(game==="crash"){s.innerHTML=`<div class="crash-screen"><div class="crash-graph"><div class="crash-line" id="crashLine"></div><div class="crash-rocket" id="crashRocket">🚀</div><div class="crash-multiplier" id="crashMultiplier">1.00x</div><div class="arcade-caption" id="crashCaption">Set your target and launch.</div></div></div>`;c.innerHTML=field("Target Multiplier","crashTargetInput",'<input id="crashTargetInput" type="number" min="1.1" max="10" step=".1" value="2.0" />',"Higher target means bigger bonus, but harder to clear.")+`<div class="casino-button-row">${btn("Launch Crash","crash-play")}</div>`}
if(game==="plinko"){let pegs=[];for(let r=0;r<7;r++)for(let col=0;col<=r+3;col++)pegs.push(`<span class="plinko-peg" style="left:${14+col*(72/(r+4))+(r%2?4:0)}%;top:${18+r*9.5}%"></span>`);s.innerHTML=`<div class="plinko-screen"><div class="plinko-board">${pegs.join("")}<div class="plinko-ball" id="plinkoBall"></div><div class="plinko-buckets">${PM.map(m=>`<span>${m}x</span>`).join("")}</div></div></div>`;c.innerHTML=`<div class="casino-button-row">${btn("Drop Ball","plinko-drop")}</div>`}
if(game==="mines"){s.innerHTML=`<div class="mines-screen"><div class="mines-grid" id="minesGrid"></div><div class="arcade-result-number" id="minesMultiplier">1.00x</div><div class="arcade-caption" id="minesCaption">Start a board. Reveal safe tiles. Cash out when it feels right.</div></div>`;c.innerHTML=field("Mines Count","minesCountInput",'<select id="minesCountInput"><option value="3">3 Mines</option><option value="5">5 Mines</option><option value="7">7 Mines</option></select>',"More mines means bigger cash-out multiplier.")+`<div class="casino-button-row">${btn("Start Mines","mines-start")}${btn("Cash Out","mines-cashout","secondary")}</div>`;drawMines()}
if(game==="slots"){s.innerHTML=`<div class="slots-screen"><div class="slot-machine"><div class="slot-marquee">${"<span></span>".repeat(12)}</div><div class="slot-reels"><div class="slot-reel" id="slotA">💎</div><div class="slot-reel" id="slotB">🦆</div><div class="slot-reel" id="slotC">🔥</div></div><div class="arcade-caption" id="slotCaption">Three matching symbols hits hardest. Two matching symbols still hit.</div></div></div>`;c.innerHTML=`<div class="casino-button-row">${btn("Spin Reels","slots-spin")}</div>`}
if(game==="scratcher"){scratch=mkScratch();s.innerHTML=`<div class="scratcher-screen"><div class="scratcher-card" id="scratcherCard"></div><div class="arcade-caption" id="scratchCaption">Reveal every tile. Three matching icons wins.</div></div>`;c.innerHTML=`<div class="casino-button-row">${btn("New Scratcher","scratch-new")}</div>`;drawScratch()}
if(game==="hilo"){hilo={cur:card(),streak:0};s.innerHTML=`<div class="hilo-screen"><div class="hilo-card"><div><strong id="hiloCardValue">${face(hilo.cur)}</strong><span>Current Card</span></div></div><div class="arcade-result-number" id="hiloStreak">0x</div><div class="arcade-caption" id="hiloCaption">Will the next card be higher or lower?</div></div>`;c.innerHTML=`<div class="casino-button-row">${btn("Higher","hilo-high")}${btn("Lower","hilo-low","secondary")}${btn("New Card","hilo-new","secondary")}</div>`}
if(game==="roulette"){s.innerHTML=`<div class="roulette-screen"><div class="roulette-wheel-wrap"><div class="roulette-pointer"></div><div class="roulette-wheel" id="rouletteWheel"></div><div class="roulette-center" id="rouletteResult">PICK<br>COLOR</div></div></div>`;c.innerHTML=field("Pick Color","roulettePickInput",'<select id="roulettePickInput"><option value="red">Red 2x</option><option value="black">Black 2x</option><option value="green">Green 14x</option></select>',"Green is rare but bigger.")+`<div class="casino-button-row">${btn("Spin Wheel","roulette-spin")}</div>`}
bind()
}
function act(a){if(a==="crash-play")playCrash();if(a==="plinko-drop")playPlinko();if(a==="mines-start")startMines();if(a==="mines-cashout")cashMines();if(a==="slots-spin")spinSlots();if(a==="scratch-new")newScratch();if(a==="hilo-high")playHilo("high");if(a==="hilo-low")playHilo("low");if(a==="hilo-new")newHilo();if(a==="roulette-spin")spinRoulette()}
async function playCrash(){let p=power(),i=$("crashTargetInput"),t=cl(parseFloat(i&&i.value)||2,1.1,10);if(i)i.value=t.toFixed(1);let ca=Math.min(12,Math.max(1,Math.pow(1/Math.max(.02,Math.random()),.58))),win=ca>=t,l=$("crashLine"),r=$("crashRocket");if(l)l.style.transform=`rotate(-${win?28:12}deg) scaleX(${Math.min(.98,ca/6)})`;if(r){r.style.left=`${Math.min(82,22+ca*7)}%`;r.style.bottom=`${Math.min(78,16+ca*8)}%`;r.style.transform=win?"rotate(-18deg)":"rotate(44deg)"}txt("crashMultiplier",ca.toFixed(2)+"x");txt("crashCaption",win?`Rocket cleared ${t.toFixed(1)}x before crash.`:`Rocket crashed at ${ca.toFixed(2)}x before target.`);await award("crash",win?p*t:0,Math.round(ca*100),win?`${t.toFixed(1)}x clear`:`${ca.toFixed(2)}x crash`,{target:t,crashAt:ca})}
async function playPlinko(){let lane=cl(Math.floor((Math.random()+Math.random())/2*PM.length),0,PM.length-1),m=PM[lane],b=$("plinkoBall");if(b){b.style.left=`${6+lane*8.8}%`;b.style.top="303px"}await award("plinko",power()*m,m*100,m?`${m}x bucket`:"dead bucket",{lane,multiplier:m})}
function mineSet(n){let s=new Set;while(s.size<n)s.add(rnd(25));return s}
function drawMines(all=false){let g=$("minesGrid");if(!g)return;g.innerHTML=Array.from({length:25}).map((_,i)=>{let is=mines&&mines.set.has(i),op=mines&&mines.open.has(i),show=all||op,cls=show?(is?"boom":"safe"):"";return `<button class="mine-tile ${cls}" type="button" data-i="${i}" ${mines&&mines.done?"disabled":""}>${show?(is?"💣":"💎"):"?"}</button>`}).join("");qa("[data-i]",g).forEach(b=>b.onclick=()=>openMine(+b.dataset.i))}
function startMines(){let n=cl(num($("minesCountInput")&&$("minesCountInput").value),3,7);mines={set:mineSet(n),open:new Set,done:false,n};drawMines();txt("minesMultiplier","1.00x");txt("minesCaption","Board armed. Safe tiles build the multiplier.");status(`Mines board started with ${n} hidden mines. Cool Points cannot go down.`)}
function mm(){return mines?1+mines.open.size*(.22+mines.n*.055):1}
async function openMine(i){if(!mines||mines.done)return status("Start a Mines board first.");if(mines.open.has(i))return;if(mines.set.has(i)){mines.done=true;drawMines(true);txt("minesCaption","Boom. No bonus, no points removed.");return award("mines",0,mines.open.size*10,"mine hit",{mines:mines.n,safeTiles:mines.open.size})}mines.open.add(i);let m=mm();drawMines();txt("minesMultiplier",m.toFixed(2)+"x");txt("minesCaption",`${mines.open.size} safe tiles. Cash out or keep moving.`);status(`Safe tile. Current cash-out bonus: +${fmt(power()*m)} Cool Points.`)}
async function cashMines(){if(!mines||mines.done||!mines.open.size)return status("Open at least one safe tile before cashing out.");mines.done=true;let m=mm();drawMines(true);txt("minesCaption",`Cashed out at ${m.toFixed(2)}x.`);await award("mines",power()*m,Math.round(m*100),`${mines.open.size} safe cashout`,{mines:mines.n,safeTiles:mines.open.size,multiplier:m})}
async function spinSlots(){let reels=[$("slotA"),$("slotB"),$("slotC")];reels.forEach(x=>x&&x.classList.add("spin"));status("Reels spinning...");setTimeout(async()=>{let r=[SY[rnd(SY.length)],SY[rnd(SY.length)],SY[rnd(SY.length)]];reels.forEach((x,i)=>{if(x){x.textContent=r[i];x.classList.remove("spin")}});let counts=r.reduce((a,s)=>(a[s]=(a[s]||0)+1,a),{}),max=Math.max(...Object.values(counts)),m=max===3?(r[0]==="🦆"?15:10):(max===2?2:0);if(r.includes("🌉")&&r.includes("🦆"))m++;txt("slotCaption",m?`Match hit for ${m}x.`:"No match. Points stayed put.");await award("slots",power()*m,m*100,m?`${m}x reel hit`:"no match",{result:r,multiplier:m})},900)}
function mkScratch(){let win=Math.random()>.48,t=SY[rnd(SY.length)],tiles=win?[t,t,t,SY[rnd(SY.length)],SY[rnd(SY.length)],SY[rnd(SY.length)]]:Array.from({length:6},()=>SY[rnd(SY.length)]);for(let i=tiles.length-1;i>0;i--){let j=rnd(i+1);[tiles[i],tiles[j]]=[tiles[j],tiles[i]]}return{tiles,rev:new Set,done:false}}
function drawScratch(){let c=$("scratcherCard");if(!c||!scratch)return;c.innerHTML=scratch.tiles.map((s,i)=>`<button class="scratch-tile ${scratch.rev.has(i)?"revealed":""}" type="button" data-s="${i}" ${scratch.done?"disabled":""}>${scratch.rev.has(i)?s:"H"}</button>`).join("");qa("[data-s]",c).forEach(b=>b.onclick=()=>revealScratch(+b.dataset.s))}
function newScratch(){scratch=mkScratch();drawScratch();txt("scratchCaption","Fresh card loaded. Reveal all six panels.");status("New HYPHSWORLD scratcher ready.")}
async function revealScratch(i){if(!scratch||scratch.done)return;scratch.rev.add(i);drawScratch();if(scratch.rev.size<6)return;let vis=Array.from(scratch.rev).map(i=>scratch.tiles[i]),counts=vis.reduce((a,s)=>(a[s]=(a[s]||0)+1,a),{}),win=Math.max(...Object.values(counts))>=3;scratch.done=true;drawScratch();txt("scratchCaption",win?"Three-match scratcher hit.":"No three-match. Points stayed safe.");await award("scratcher",win?power()*6:0,win?600:1,win?"three match":"no match",{tiles:vis})}
function card(){return CV[rnd(CV.length)]}
function face(v){return v===14?"A":v===13?"K":v===12?"Q":v===11?"J":String(v)}
function newHilo(){hilo={cur:card(),streak:0};txt("hiloCardValue",face(hilo.cur));txt("hiloStreak","0x");txt("hiloCaption","Will the next card be higher or lower?");status("New High-Low card loaded.")}
async function playHilo(guess){if(!hilo)newHilo();let n=card(),cur=hilo.cur,ok=guess==="high"?n>=cur:n<=cur;hilo.cur=n;txt("hiloCardValue",face(n));if(ok){hilo.streak++;let m=1+hilo.streak*1.5;txt("hiloStreak",hilo.streak+"x");txt("hiloCaption",`Correct. Streak ${hilo.streak}.`);await award("hilo",power()*m,Math.round(m*100),`${hilo.streak} streak`,{guess,next:n,streak:hilo.streak})}else{hilo.streak=0;txt("hiloStreak","0x");txt("hiloCaption","Wrong call. No bonus, no points removed.");await award("hilo",0,1,"wrong call",{guess,next:n})}}
async function spinRoulette(){let pick=String($("roulettePickInput")&&$("roulettePickInput").value||"red"),roll=Math.random(),res=roll<.06?"green":roll<.53?"red":"black",m=res==="green"?14:2,win=res===pick;rot+=720+rnd(720);let w=$("rouletteWheel");if(w)w.style.transform=`rotate(${rot}deg)`;let r=$("rouletteResult");if(r)r.innerHTML=`${res.toUpperCase()}<br>${win?"HIT":"MISS"}`;await award("roulette",win?power()*m:0,m*100,win?`${res} hit`:`${res} miss`,{pick,result:res,multiplier:m})}
function boot(){let y=$("year");if(y)y.textContent=new Date().getFullYear();qa("[data-game]").forEach(b=>b.onclick=()=>setGame(b.dataset.game));drawRec();refreshUser();setGame(game)}
document.addEventListener("DOMContentLoaded",boot);
})();