(function(){'use strict';var follow=document.getElementById('followCreator');var share=document.getElementById('shareCreator');var toast=document.getElementById('worldToast');var audio=document.getElementById('creatorAudio');var play=document.getElementById('playTrack');var progress=document.getElementById('trackProgress');var shell=document.getElementById('progressShell');var time=document.getElementById('trackTime');var title=document.getElementById('activeTitle');var meta=document.getElementById('activeMeta');var cover=document.getElementById('activeCover');var key='hyphsworld.creator.hyph-life.following';var rewardPrefix='hyphsworld.creator.hyph-life.reward.';var toastTimer;
function show(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){toast.classList.remove('show')},2600)}
function following(){try{return localStorage.getItem(key)==='true'}catch(e){return false}}
function renderFollow(){var active=following();follow.classList.toggle('is-following',active);follow.setAttribute('aria-pressed',String(active));follow.textContent=active?'✓ Following HYPH LIFE':'＋ Follow HYPH LIFE'}
function awardOnce(amount,reason,rewardId){var rewardKey=rewardPrefix+rewardId;try{if(localStorage.getItem(rewardKey)==='true')return;if(window.HWPoints&&typeof window.HWPoints.getState==='function'&&!window.HWPoints.getState().user){show('Log in to save Cool Points');return}}catch(e){}if(window.HWPoints&&typeof window.HWPoints.add==='function')window.HWPoints.add(amount,reason,{creator_id:'hyph-life',reward_id:rewardId}).then(function(state){if(state&&state.user){try{localStorage.setItem(rewardKey,'true')}catch(e){}show('+'+amount+' Cool Points saved')}}).catch(function(){show('Could not save Cool Points yet')})}
follow.addEventListener('click',function(){var next=!following();try{localStorage.setItem(key,String(next))}catch(e){}renderFollow();show(next?'You’re following Creator #001':'Creator unfollowed');if(next)awardOnce(10,'creator_follow_hyph_life','follow')});
share.addEventListener('click',async function(){var data={title:'HYPH LIFE — Creators World',text:'Enter HYPH LIFE’s world on HYPHSWORLD.',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);show('Profile link copied')}}catch(e){if(e&&e.name!=='AbortError')show('Share link ready: '+location.href)}});
function format(seconds){if(!Number.isFinite(seconds))return'0:00';var m=Math.floor(seconds/60);var s=Math.floor(seconds%60);return m+':'+String(s).padStart(2,'0')}
function renderAudio(){play.textContent=audio.paused?'▶':'❚❚';play.setAttribute('aria-label',(audio.paused?'Play ':'Pause ')+title.textContent);var percent=audio.duration?audio.currentTime/audio.duration*100:0;progress.style.width=percent+'%';time.textContent=format(audio.currentTime)}
play.addEventListener('click',function(){if(audio.paused)audio.play().catch(function(){show('Tap play again to start audio')});else audio.pause()});audio.addEventListener('play',renderAudio);audio.addEventListener('pause',renderAudio);audio.addEventListener('timeupdate',renderAudio);audio.addEventListener('ended',function(){awardOnce(5,'creator_track_complete','track-'+title.textContent.toLowerCase().replace(/[^a-z0-9]+/g,'-'));renderAudio()});
shell.addEventListener('click',function(event){if(!audio.duration)return;var rect=shell.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width))*audio.duration});
document.querySelectorAll('.track').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('.track').forEach(function(item){item.classList.remove('is-active')});button.classList.add('is-active');audio.src=button.dataset.src;cover.src=button.dataset.cover;cover.alt=button.dataset.title+' cover artwork';title.textContent=button.dataset.title;meta.textContent=button.dataset.meta;renderAudio();audio.play().catch(function(){show('Tap the green play button to listen')})})});
document.getElementById('year').textContent=new Date().getFullYear();renderFollow();renderAudio()})();
