(function(){
 const duck=["I’m in the site now. Don’t act regular.","Tap something. Cool Points don’t earn themselves.","Full Player open. Vault open. Merch open. We major.","HYPHSWORLD got rooms now. Don’t get lost."];
 const buck=["Code first.","Denied blood.","I need you leave.","Vault security active.","Access gotta be earned."];
 function line(type){const p=type==="buck"?buck:duck;return p[Math.floor(Math.random()*p.length)]}
 function pop(text){let p=document.querySelector(".hw-points-pop");if(!p){p=document.createElement("div");p.className="hw-points-pop";document.body.appendChild(p)}p.textContent=text;p.classList.add("show");clearTimeout(p._t);p._t=setTimeout(()=>p.classList.remove("show"),1700)}
 function speak(type,text){const s=document.querySelector(".hw-speech");if(!s)return;s.textContent=text||line(type);s.classList.add("show");clearTimeout(s._t);s._t=setTimeout(()=>s.classList.remove("show"),3900)}
 function points(amount,label){let v=Number(localStorage.getItem("hyphsworldCoolPoints")||203)+amount;localStorage.setItem("hyphsworldCoolPoints",String(v));document.querySelectorAll("#coolPoints,#vaultPoints").forEach(e=>e.textContent=String(v));pop("+"+amount+" COOL POINTS"+(label?" • "+label:""))}
 function build(){if(document.querySelector(".hw-float-wrap"))return;let w=document.createElement("aside");w.className="hw-float-wrap";w.innerHTML='<div class="hw-speech" role="status" aria-live="polite"></div><div class="hw-mascot-row"><button class="hw-mascot-btn hw-duck-btn" type="button" aria-label="Talk to Duck Sauce"><img src="duck-sauce.jpg" alt=""></button><button class="hw-mascot-btn hw-buck-btn" type="button" aria-label="Talk to BuckTheBodyguard"><img src="buck-thebodyguard.jpg" alt=""></button></div>';document.body.appendChild(w);document.querySelector(".hw-duck-btn").onclick=()=>{speak("duck");points(2,"DUCK TAP")};document.querySelector(".hw-buck-btn").onclick=()=>{speak("buck");points(1,"BUCK CHECK")}}
 function wire(){document.querySelectorAll("a,button").forEach(el=>{if(el.dataset.hwWired)return;el.dataset.hwWired="1";el.addEventListener("click",()=>{let t=(el.textContent||"").toLowerCase(),h=(el.getAttribute("href")||"").toLowerCase();if(t.includes("vault")||h.includes("vault")){speak("buck","Buck checking access. Code better be right.");points(1,"VAULT TAP")}else if(t.includes("play")||h.includes("player")){speak("duck","Music motion. Run it up.")}else if(t.includes("merch")||h.includes("shop")||h.includes("cash")||h.includes("py.pl")){speak("duck","Supporter lane. Boss motion.");points(3,"MERCH TAP")}}, {passive:true})});let form=document.getElementById("vaultForm"),inp=document.getElementById("vaultCode");if(form&&inp&&!form.dataset.hwVaultWired){form.dataset.hwVaultWired="1";form.addEventListener("submit",()=>{let c=inp.value.trim().toUpperCase(),ok=["510","HYPH","DUCK","AMS","RICHMOND","QUARANTINE","WORLD5","CASINO"].includes(c);if(ok){speak("buck","Access approved. Don’t embarrass me in here.");points(10,"CODE HIT")}else speak("buck","Denied blood. I need you leave.")},{passive:true})}}
 window.addEventListener("hyphsworld:addpoints",e=>pop("+"+(e.detail?.amount||1)+" COOL POINTS"));
 function init(){build();wire();setTimeout(()=>speak("duck","Duck Sauce online. Tap around and earn points."),900);setInterval(()=>{if(!document.hidden)speak(Math.random()>.72?"buck":"duck")},30000)}
 document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
