window.HW_HYPHSWORLD5_COVER_SOURCES = ['hyphsworld-5.jpg','hyphsworld5.jpg','HYPHSWORLD5.jpg','hyphsworld-5-cover.jpg','assets/images/hyphsworld-5.jpg'];
window.HW_HYPHSWORLD5_TRACKS = [
  {
    "number": "01",
    "title": "Whats Hannin",
    "artist": "Hyph Life",
    "meta": "HYPHSWORLD 5",
    "code": "WH",
    "sources": [
      "whats-hannin.mp3",
      "assets/audio/whats-hannin.mp3",
      "audio/whats-hannin.mp3",
      "music/whats-hannin.mp3",
      "what-hannin.mp3",
      "assets/audio/what-hannin.mp3",
      "audio/what-hannin.mp3",
      "music/what-hannin.mp3",
      "whats hannin.mp3",
      "assets/audio/whats hannin.mp3",
      "audio/whats hannin.mp3",
      "music/whats hannin.mp3",
      "Whats Hannin.mp3",
      "assets/audio/Whats Hannin.mp3",
      "audio/Whats Hannin.mp3",
      "music/Whats Hannin.mp3",
      "WHAT'S HANNIN.mp3",
      "assets/audio/WHAT'S HANNIN.mp3",
      "audio/WHAT'S HANNIN.mp3",
      "music/WHAT'S HANNIN.mp3",
      "what_s_hannin.mp3",
      "assets/audio/what_s_hannin.mp3",
      "audio/what_s_hannin.mp3",
      "music/what_s_hannin.mp3"
    ],
    "art": [
      "hyphsworld-5.jpg",
      "hyphsworld5.jpg",
      "HYPHSWORLD5.jpg",
      "hyphsworld-5-cover.jpg",
      "assets/images/hyphsworld-5.jpg"
    ]
  },
  {
    "number": "02",
    "title": "Bout You",
    "artist": "Hyph Life",
    "meta": "HYPHSWORLD 5",
    "code": "BY",
    "sources": [
      "bout-you.mp3",
      "assets/audio/bout-you.mp3",
      "audio/bout-you.mp3",
      "music/bout-you.mp3",
      "Bout You.mp3",
      "assets/audio/Bout You.mp3",
      "audio/Bout You.mp3",
      "music/Bout You.mp3",
      "BOUT YOU.mp3",
      "assets/audio/BOUT YOU.mp3",
      "audio/BOUT YOU.mp3",
      "music/BOUT YOU.mp3",
      "bout_you.mp3",
      "assets/audio/bout_you.mp3",
      "audio/bout_you.mp3",
      "music/bout_you.mp3"
    ],
    "art": [
      "hyphsworld-5.jpg",
      "hyphsworld5.jpg",
      "HYPHSWORLD5.jpg",
      "hyphsworld-5-cover.jpg",
      "assets/images/hyphsworld-5.jpg"
    ]
  },
  {
    "number": "03",
    "title": "Mula",
    "artist": "Hyph Life",
    "meta": "HYPHSWORLD 5",
    "code": "MULA",
    "sources": [
      "mula.mp3",
      "assets/audio/mula.mp3",
      "audio/mula.mp3",
      "music/mula.mp3",
      "Mula.mp3",
      "assets/audio/Mula.mp3",
      "audio/Mula.mp3",
      "music/Mula.mp3",
      "MULA.mp3",
      "assets/audio/MULA.mp3",
      "audio/MULA.mp3",
      "music/MULA.mp3"
    ],
    "art": [
      "hyphsworld-5.jpg",
      "hyphsworld5.jpg",
      "HYPHSWORLD5.jpg",
      "hyphsworld-5-cover.jpg",
      "assets/images/hyphsworld-5.jpg"
    ]
  },
  {
    "number": "04",
    "title": "No Trace snip",
    "artist": "Hyph Life",
    "meta": "HYPHSWORLD 5",
    "code": "TRACE",
    "sources": [
      "no-trace-snip.mp3",
      "assets/audio/no-trace-snip.mp3",
      "audio/no-trace-snip.mp3",
      "music/no-trace-snip.mp3",
      "no-trace.mp3",
      "assets/audio/no-trace.mp3",
      "audio/no-trace.mp3",
      "music/no-trace.mp3",
      "No Trace snip.mp3",
      "assets/audio/No Trace snip.mp3",
      "audio/No Trace snip.mp3",
      "music/No Trace snip.mp3",
      "NO TRACE SNIP.mp3",
      "assets/audio/NO TRACE SNIP.mp3",
      "audio/NO TRACE SNIP.mp3",
      "music/NO TRACE SNIP.mp3",
      "no_trace_snip.mp3",
      "assets/audio/no_trace_snip.mp3",
      "audio/no_trace_snip.mp3",
      "music/no_trace_snip.mp3"
    ],
    "art": [
      "hyphsworld-5.jpg",
      "hyphsworld5.jpg",
      "HYPHSWORLD5.jpg",
      "hyphsworld-5-cover.jpg",
      "assets/images/hyphsworld-5.jpg"
    ]
  },
  {
    "number": "05",
    "title": "Wikked Wayz",
    "artist": "Hyph Life",
    "meta": "HYPHSWORLD 5",
    "code": "WAYZ",
    "sources": [
      "wikked-wayz.mp3",
      "assets/audio/wikked-wayz.mp3",
      "audio/wikked-wayz.mp3",
      "music/wikked-wayz.mp3",
      "Wikked Wayz.mp3",
      "assets/audio/Wikked Wayz.mp3",
      "audio/Wikked Wayz.mp3",
      "music/Wikked Wayz.mp3",
      "WIKKED WAYZ.mp3",
      "assets/audio/WIKKED WAYZ.mp3",
      "audio/WIKKED WAYZ.mp3",
      "music/WIKKED WAYZ.mp3",
      "wikked_wayz.mp3",
      "assets/audio/wikked_wayz.mp3",
      "audio/wikked_wayz.mp3",
      "music/wikked_wayz.mp3",
      "wicked-wayz.mp3",
      "assets/audio/wicked-wayz.mp3",
      "audio/wicked-wayz.mp3",
      "music/wicked-wayz.mp3"
    ],
    "art": [
      "hyphsworld-5.jpg",
      "hyphsworld5.jpg",
      "HYPHSWORLD5.jpg",
      "hyphsworld-5-cover.jpg",
      "assets/images/hyphsworld-5.jpg"
    ]
  },
  {
    "number": "06",
    "title": "With Me",
    "artist": "Hyph Life",
    "meta": "HYPHSWORLD 5",
    "code": "WITHME",
    "sources": [
      "with-me.mp3",
      "assets/audio/with-me.mp3",
      "audio/with-me.mp3",
      "music/with-me.mp3",
      "With Me.mp3",
      "assets/audio/With Me.mp3",
      "audio/With Me.mp3",
      "music/With Me.mp3",
      "WITH ME.mp3",
      "assets/audio/WITH ME.mp3",
      "audio/WITH ME.mp3",
      "music/WITH ME.mp3",
      "with_me.mp3",
      "assets/audio/with_me.mp3",
      "audio/with_me.mp3",
      "music/with_me.mp3"
    ],
    "art": [
      "hyphsworld-5.jpg",
      "hyphsworld5.jpg",
      "HYPHSWORLD5.jpg",
      "hyphsworld-5-cover.jpg",
      "assets/images/hyphsworld-5.jpg"
    ]
  }
];
