if (!window.HWAuth) { location.href = "auth.html?next=login.html"; }
HWAuth.getSession().then(function(s){ if(!s){ location.href = "auth.html?next=login.html"; }});
const AUTH_KEY="hyphsworld_vault_access",AUTH_TIME_KEY="hyphsworld_vault_access_time",ACCESS_DURATION_MS=14400000;
const ALLOWED_HASHES=["651d8948587739f3c0aa840fd250b5b547b98a83a9b84aa24800ff1293dc8ed9"];
const form=document.getElementById("accessForm"),input=document.getElementById("accessCode"),toggle=document.getElementById("toggleCode"),terminal=document.getElementById("terminalCard"),terminalStatus=document.getElementById("terminalStatus"),message=document.getElementById("accessMessage"),scanStage=document.getElementById("scanStage"),scanReadout=document.getElementById("scanReadout"),statusText=document.getElementById("statusText"),modeText=document.getElementById("modeText"),scannerMode=document.getElementById("scannerMode"),scanLineA=document.getElementById("scanLineA"),scanLineB=document.getElementById("scanLineB"),scanLineC=document.getElementById("scanLineC");
const normalize=v=>String(v||"").trim().toUpperCase().replace(/\s+/g,"");
async function sha256(t){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function msg(t,c=""){message.textContent=t;message.classList.remove("error","success");if(c)message.classList.add(c)}
function setStatus(main,status,mode,scanner,readout,a,b,c){terminalStatus.textContent=main;statusText.textContent=status;modeText.textContent=mode;scannerMode.textContent=scanner;scanReadout.textContent=readout;scanLineA.textContent=a;scanLineB.textContent=b;scanLineC.textContent=c}
function saveAccess(){sessionStorage.setItem(AUTH_KEY,"granted");sessionStorage.setItem(AUTH_TIME_KEY,String(Date.now()))}
function hasAccess(){return sessionStorage.getItem(AUTH_KEY)==="granted"&&(Date.now()-Number(sessionStorage.getItem(AUTH_TIME_KEY)||0)<ACCESS_DURATION_MS)}
function target(){const f=new URLSearchParams(location.search).get("from");return new Set(["vault.html","hidden-casino.html","quarantine-mixtape.html","level-1.html","level1.html","vault-level-1.html"]).has(f)?f:"vault.html"}
function reset(){scanStage.classList.remove("is-checking","is-scanning","is-cleared","is-opening","is-transporting")}
function deny(){terminal.classList.remove("is-unlocked");reset();setStatus("Locked","Locked","Code Check","Denied","ACCESS DENIED","DNA: BLOCKED","BRAND: LOCKED","DUCK: LAUGHING");msg("Access denied. Duck Sauce said try that again slower.","error");input.value="";input.focus();terminal.animate([{transform:"translateX(0)"},{transform:"translateX(-8px)"},{transform:"translateX(8px)"},{transform:"translateX(0)"}],{duration:220,iterations:2})}
function run(){reset();terminal.classList.add("is-unlocked");scanStage.classList.add("is-checking");setStatus("Scanning","Scanning","Bio Rails","Rail Sweep","RAIL SWEEP ACTIVE","DNA: READING","BRAND: AMS WEST","DUCK: TALKING FAST");msg("Code accepted. High-tech scan running…","success");setTimeout(()=>{scanStage.classList.add("is-scanning");setStatus("Scanning","Scanning","Body Scan","Live","BODY SCAN ACTIVE","DNA: LOCKING","BRAND: VERIFIED","DUCK: STILL TALKING")},700);setTimeout(()=>{scanStage.classList.remove("is-scanning");scanStage.classList.add("is-cleared");setStatus("Cleared","Cleared","Smoke Burst","Cleared","ACCESS GRANTED","DNA: FUNKY","BRAND: VERIFIED","DUCK: TOO LOUD");msg("Access granted. Smoke burst loading…","success")},3200);setTimeout(()=>{scanStage.classList.add("is-transporting");setStatus("Transport","Transport","Vault Floor","Transport","TRANSPORT ACTIVE","DNA: SAVED","BRAND: LIVE","DUCK: IN THE WAY");msg("Transport active. Opening Vault Floor…","success")},4450);setTimeout(()=>{location.href=target()},5700)}
if(hasAccess()){terminal.classList.add("is-unlocked");setStatus("Ready","Unlocked","Vault Floor","Ready","SESSION VERIFIED","DNA: READY","BRAND: VERIFIED","DUCK: TALKING");msg("Access already active for this session.","success")}
toggle.addEventListener("click",()=>{const s=input.type==="text";input.type=s?"password":"text";toggle.textContent=s?"Show":"Hide";input.focus()});
form.addEventListener("submit",async e=>{e.preventDefault();const code=normalize(input.value);if(!code){msg("Enter the code first P.","error");input.focus();return}reset();scanStage.classList.add("is-checking");msg("Checking code…");setStatus("Checking","Checking","Hash Check","Code Check","CODE HASH CHECK","DNA: WAITING","BRAND: WAITING","DUCK: LISTENING");try{const h=await sha256(code);if(!ALLOWED_HASHES.includes(h))return deny();saveAccess();run()}catch(err){console.error(err);msg("Browser blocked the scanner. Refresh once and try again.","error")}});
