function grantLevelOneTransport(){try{sessionStorage.setItem('HW_LEVEL1_TRANSPORT_V6',JSON.stringify({level:'level-one',route:'quarantine-mixtape',grantedAt:Date.now(),source:'vault-floor'}));}catch(error){}}
document.querySelectorAll('a[href="quarantine-mixtape.html"],a[href="level-1.html"]').forEach((link)=>{link.addEventListener('click',grantLevelOneTransport);});

const scanButton=document.getElementById("runVaultScan"),scanStage=document.getElementById("scanStage"),scanReadout=document.getElementById("scanReadout"),gateStatus=document.getElementById("gateStatus"),statusText=document.getElementById("statusText"),modeText=document.getElementById("modeText"),scannerMode=document.getElementById("scannerMode"),scanLineA=document.getElementById("scanLineA"),scanLineB=document.getElementById("scanLineB"),scanLineC=document.getElementById("scanLineC"),vaultNote=document.getElementById("vaultNote"),transportOverlay=document.getElementById("transportOverlay");
const spinButton=document.getElementById("spinButton"),rulesButton=document.getElementById("rulesButton"),closeRules=document.getElementById("closeRules"),rulesModal=document.getElementById("rulesModal"),slotStatus=document.getElementById("slotStatus"),slotMessage=document.getElementById("slotMessage"),reelEls=[document.getElementById("reel1"),document.getElementById("reel2"),document.getElementById("reel3")],pointsDisplay=document.getElementById("pointsDisplay"),coolPointsText=document.getElementById("coolPointsText");
const levelOneCandidates=["quarantine-mixtape.html","level-1.html","level1.html","vault-level-1.html"],SLOT_ICONS=["💨","🎰","💎","01","AMS","💰","7"];
function getPoints(){return Number(localStorage.getItem("hyphsworld_cool_points")||0)}function setPoints(v){localStorage.setItem("hyphsworld_cool_points",String(v));if(pointsDisplay)pointsDisplay.textContent=v;if(coolPointsText)coolPointsText.textContent=v}setPoints(getPoints());
function resetScan(){scanStage.classList.remove("is-checking","is-scanning","is-cleared","is-opening","is-transporting")}function setScanner(status,mode,scanner,readout,a,b,c,note){gateStatus.textContent=status;statusText.textContent=status;modeText.textContent=mode;scannerMode.textContent=scanner;scanReadout.textContent=readout;scanLineA.textContent=a;scanLineB.textContent=b;scanLineC.textContent=c;if(note)vaultNote.textContent=note}
async function findLevelOne(){for(const url of levelOneCandidates){try{const r=await fetch(url,{method:"HEAD",cache:"no-store"});if(r.ok)return url}catch(e){}}return"quarantine-mixtape.html"}
async function runVaultScan(){resetScan();scanStage.classList.add("is-checking");scanButton.disabled=true;scanButton.textContent="Scanning...";setScanner("Scanning","Bio Rails","Rail Sweep","RAIL SWEEP ACTIVE","DNA: READING","BRAND: AMS WEST","DUCK: TALKING FAST","High-tech scanner running. Rail sweep active.");setTimeout(()=>{scanStage.classList.add("is-scanning");setScanner("Scanning","Body Scan","Live","BODY SCAN ACTIVE","DNA: LOCKING","BRAND: VERIFIED","DUCK: STILL TALKING","Body scan running. Do not move.")},700);setTimeout(()=>{scanStage.classList.remove("is-scanning");scanStage.classList.add("is-cleared");setScanner("Cleared","Smoke Burst","Cleared","ACCESS GRANTED","DNA: FUNKY","BRAND: VERIFIED","DUCK: TOO LOUD","Scan clear. Smoke burst loading.")},3200);setTimeout(()=>{scanStage.classList.add("is-opening");setScanner("Opening","Scan-Bar Door","Door Open","SCAN-BAR DOOR OPENING","DNA: SAVED","BRAND: LIVE","DUCK: IN THE WAY","Scan-bar gate opening.")},4200);setTimeout(()=>{scanStage.classList.add("is-transporting");setScanner("Transport","Level 1","Transport","TRANSPORT ACTIVE","DNA: SAVED","BRAND: LIVE","DUCK: STILL IN THE WAY","Transport charging. Level 1 loading.")},5300);setTimeout(async()=>{transportOverlay.classList.add("is-active");grantLevelOneTransport();location.href=await findLevelOne()},6600)}
if(scanButton)scanButton.addEventListener("click",runVaultScan);
function randIcon(){return SLOT_ICONS[Math.floor(Math.random()*SLOT_ICONS.length)]}function spinReels(){spinButton.disabled=true;slotStatus.textContent="Spinning";slotMessage.textContent="Duck Sauce says let it ride...";let ticks=0;const interval=setInterval(()=>{reelEls.forEach(el=>el.textContent=randIcon());ticks++;if(ticks>12){clearInterval(interval);const final=[randIcon(),randIcon(),randIcon()];reelEls.forEach((el,i)=>el.textContent=final[i]);const counts={};final.forEach(x=>counts[x]=(counts[x]||0)+1);const max=Math.max(...Object.values(counts));let won=max===3?30:max===2?10:1;slotStatus.textContent=max===3?"Jackpot":max===2?"Nice Hit":"Close Call";slotMessage.textContent=max===3?"Big win. 3 of a kind. +30 Cool Points.":max===2?"2 matched. +10 Cool Points.":"No match. Buck gave you a pity point. +1 Cool Point.";setPoints(getPoints()+won);spinButton.disabled=false}},120)}
if(spinButton)spinButton.addEventListener("click",spinReels);if(rulesButton)rulesButton.addEventListener("click",()=>rulesModal.classList.add("is-open"));if(closeRules)closeRules.addEventListener("click",()=>rulesModal.classList.remove("is-open"));if(rulesModal)rulesModal.addEventListener("click",e=>{if(e.target===rulesModal)rulesModal.classList.remove("is-open")});
